### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-T09-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T09-4/main#225]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @hotspur1997 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-4/main/pull/188 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/175 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/170 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/164 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/161 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/149 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @riyas97 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-4/main/pull/216 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/212 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/211 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/204 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/201 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/194 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/192 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/186 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/183 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/178 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/175 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/174 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/173 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/160 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/159 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/158 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/148 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/147 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/20 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @nwenhui for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-4/main/pull/190 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/189 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/175 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/171 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/146 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @pdotdeep for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-4/main/pull/184 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/180 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/141 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/176 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/175 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/172 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/168 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/161 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/148 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @jylee-git

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
