### ISSUE TITLE
Feedback on week 9 project progress for CS2113T-T09-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T09-4/main#89]
## Team progress for `v1.2`
* [x] Team PR created to the upstream repository with the title `[AY1920S1-CS2113T-T09-4] Contact List Pro`(:exclamation:)
* Milestone `v1.2` properly managed:
   * [x] A suitable deadline 2019-10-16 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-T09-4/main/pull/84 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/83 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/78 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/77 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/76 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/73 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/72 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/71 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/68 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/67 https://github.com/AY1920S1-CS2113T-T09-4/main/pull/66 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/65 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/64 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/31 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/29 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/14 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/8 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/3 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/2 (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
   * [x] Code tagged as `v1.2`(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.2` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone v1.3 planned:
   * [x] A suitable deadline 2019-10-30 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-T09-4/main/pull/87 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/70 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/30 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/21 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/17 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/12 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/11 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/10 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/6 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/4 (:heavy_check_mark: well done!)
## Individual progress of @hotspur1997 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-4/main/issues/14 (:heavy_check_mark: well done!)
## Individual progress of @riyas97 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-4/main/issues/31 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/29 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/3 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/2 (:heavy_check_mark: well done!)
## Individual progress of @nwenhui for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-4/main/issues/67 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/8 (:heavy_check_mark: well done!)
## Individual progress of @pdotdeep for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-4/main/issues/71 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/65 https://github.com/AY1920S1-CS2113T-T09-4/main/issues/64 (:heavy_check_mark: well done!)

Tutor: @jylee-git

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-17 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
